name: Mascarar Data
js_form:
    - ../../js/masks/js/jquery.meio.js
    - ../../js/masks/js/masks.js
    - ../../../../plugins/jquery-ui/jquery-ui.min.js
    - ../../js/masks/js/datetimepicker.js
css_form:
    - ../../../../plugins/jquery-ui/jquery-ui.css
attr:
    alt: date
    class: add-mask date-mod